#ifndef IDC_STATIC
#define IDC_STATIC (-1)
#endif

#define IDR_MTTTYMENU                           101
#define IDR_MTTTYACCELERATOR                    102
#define IDD_TOOLBARSETTINGS                     103
#define ID_TTYWINDOW				104
#define IDD_ABOUT                               105
#define IDD_STATUSDIALOG                        106
#define IDD_COMMEVENTSDLG                       107
#define IDD_FLOWCONTROLDLG                      108
#define IDD_TIMEOUTSDLG                         110
#define IDD_GETADWORD                           111
#define IDI_APPICON                             112
#define IDI_APPICON2                            113
#define IDI_APPICON3                            114
#define IDI_APPICON4                            115
#define IDC_PORTCOMBO                           1000
#define IDC_BAUDCOMBO                           1001
#define IDC_PARITYCOMBO                         1002
#define IDC_DATABITSCOMBO                       1003
#define IDC_STATCTS                             1004
#define IDC_STOPBITSCOMBO                       1005
#define IDC_STATDSR                             1010
#define IDC_STATRING                            1011
#define IDC_STATRLSD                            1012
#define IDC_FONTBTN                             1013
#define IDC_ABORTBTN                            1014
#define IDC_TRANSFERPROGRESS                    1015
#define IDC_MODEMSTATUSGRP                      1020
#define IDC_COMMEVENTSBTN                       1021
#define IDC_EVBREAKBTN                          1022
#define IDC_EVCTSBTN                            1023
#define IDC_EVDSRBTN                            1024
#define IDC_EVERRBTN                            1025
#define IDC_EVRINGBTN                           1030
#define IDC_EVRLSDBTN                           1031
#define IDC_EVRXCHARBTN                         1032
#define IDC_EVRXFLAGBTN                         1033
#define IDC_EVTXEMPTYBTN                        1034
#define IDC_FLAGEDIT                            1035
#define IDC_DEFAULTSBTN                         1040
#define IDC_LFBTN                               1041
#define IDC_STATUSEDIT                          1042
#define IDC_FLAGCHAR                            1043
#define IDC_FLOWCONTROLBTN                      1044
#define IDC_CTSOUTCHK                           1045
#define IDC_DSROUTCHK                           1050
#define IDC_DTRCONTROLCOMBO                     1051
#define IDC_DSRINCHK                            1052
#define IDC_XONXOFFOUTCHK                       1053
#define IDC_XONXOFFINCHK                        1054
#define IDC_XONLIMITEDIT                        1055
#define IDC_XOFFLIMITEDIT                       1060
#define IDC_XONCHAREDIT                         1061
#define IDC_XOFFCHAREDIT                        1062
#define IDC_RTSCONTROLCOMBO                     1063
#define IDC_RTSCTSBTN                           1064
#define IDC_XOFFXONBTN                          1065
#define IDC_XONCHARDISP                         1070
#define IDC_XOFFCHARDISP                        1071
#define IDC_DTRDSRBTN                           1072
#define IDC_PICTURE                             1073
#define IDC_TIMEOUTSBTN                         1074
#define IDC_READINTERVALEDIT                    1075
#define IDC_READMULTIPLIEREDIT                  1080
#define IDC_READCONSTANTEDIT                    1081
#define IDC_WRITEMULTIPLIEREDIT                 1082
#define IDC_WRITECONSTANTEDIT                   1083
#define IDC_NONEBTN                             1084
#define IDC_OSVERSIONINFO                       1085
#define IDC_TXAFTERXOFFSENTCHK                  1090
#define IDC_CTSHOLDCHK                          1091
#define IDC_DSRHOLDCHK                          1092
#define IDC_RLSDHOLDCHK                         1093
#define IDC_XOFFHOLDCHK                         1094
#define IDC_XOFFSENTCHK                         1095
#define IDC_EOFSENTCHK                          1100
#define IDC_TXIMCHK                             1101
#define IDC_TXCHAREDIT                          1102
#define IDC_RXCHAREDIT                          1103
#define IDC_PDP8MSBCHK				1104
#define IDC_LOCALECHOCHK                        1105
#define IDC_DISPLAYERRORSCHK                    1110
#define IDC_AUTOWRAPCHK                         1111
#define IDC_NOREADINGCHK                        1112
#define IDC_NOWRITINGCHK                        1113
#define IDC_NOSTATUSCHK                         1114
#define IDC_NOEVENTSCHK                         1115
#define IDC_DWORDSTATIC                         1120
#define IDC_DWORDEDIT                           1121
#define IDC_DISPLAYTIMEOUTS                     1122
#define ID_FILE_EXIT                            40001
#define ID_HELP_ABOUTMTTTY                      40002
#define ID_FILE_CONNECT                         40004
#define ID_FILE_DISCONNECT                      40005
#define ID_TTY_CLEAR                            40008
#define ID_TRANSFER_SENDFILETEXT                40010
#define ID_TRANSFER_RECEIVEFILETEXT             40011
#define ID_TRANSFER_SENDREPEATEDLY              40012
#define ID_TRANSFER_ABORTSENDING                40016
#define ID_TRANSFER_ABORTREPEATEDSENDING        40018
